# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ce42cebd506c3b530d1a131fc6a8b24d025f329edfc39b5cf5be174c7083344e6b966a3c93c3c76fa41ffa4a19a4edc61837bace26c3c7203980f8422f9411c

test:
  secret_key_base: 89df58282fe4525962a748fed6cce737eac43b8a87333276e666ebd230ab093869f3d10eca0673c82e4ecbf23d8c843d8a48930be9b08e540e0b6502c68fa737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
